//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Winfocus_CS : DbContext
    {
        public Winfocus_CS()
            : base("name=Winfocus_CS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAccademicYear> TblAccademicYears { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TblSyllabu> TblSyllabus { get; set; }
        public virtual DbSet<TblGrade> TblGrades { get; set; }
        public virtual DbSet<TblStream> TblStreams { get; set; }
        public virtual DbSet<TblSubject> TblSubjects { get; set; }
        public virtual DbSet<TblCourse> TblCourses { get; set; }
        public virtual DbSet<TblChapter> TblChapters { get; set; }
        public virtual DbSet<TblSubChapter> TblSubChapters { get; set; }
        public virtual DbSet<TblModule> TblModules { get; set; }
        public virtual DbSet<TblNoteType> TblNoteTypes { get; set; }
        public virtual DbSet<TblFeeDetail> TblFeeDetails { get; set; }
        public virtual DbSet<TblPaymentMode> TblPaymentModes { get; set; }
        public virtual DbSet<TblRelationship> TblRelationships { get; set; }
        public virtual DbSet<TblStudent_Mark_Scored> TblStudent_Mark_Scored { get; set; }
        public virtual DbSet<TblMaterial> TblMaterials { get; set; }
        public virtual DbSet<TblRegistrationBatch> TblRegistrationBatches { get; set; }
        public virtual DbSet<TblRegistrationBatchTime> TblRegistrationBatchTimes { get; set; }
        public virtual DbSet<TblStudent_Payment_Terms> TblStudent_Payment_Terms { get; set; }
        public virtual DbSet<TblDicountCoupen> TblDicountCoupens { get; set; }
        public virtual DbSet<TblTax> TblTaxes { get; set; }
        public virtual DbSet<TblStudent_Fee> TblStudent_Fee { get; set; }
        public virtual DbSet<TblStudent_Payment_History> TblStudent_Payment_History { get; set; }
        public virtual DbSet<TblTargetExam> TblTargetExams { get; set; }
        public virtual DbSet<TblTargetYear> TblTargetYears { get; set; }
        public virtual DbSet<TblStudent_Parent_Basic> TblStudent_Parent_Basic { get; set; }
        public virtual DbSet<TblSTudentBasicDetail> TblSTudentBasicDetails { get; set; }
        public virtual DbSet<TblDTPRegistration> TblDTPRegistrations { get; set; }
    
        public virtual int SPinsertRole(Nullable<int> roleId, Nullable<int> userId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPinsertRole", roleIdParameter, userIdParameter);
        }
    }
}
