//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAttendExam
    {
        public int Id { get; set; }
        public int ExamId { get; set; }
        public int StudentId { get; set; }
        public int IsAttented { get; set; }
        public string OptMark { get; set; }
        public int IsDeletedEr { get; set; }
        public System.DateTime CreatedDateAe { get; set; }
        public int TQ { get; set; }
        public int TA { get; set; }
        public int CA { get; set; }
        public int IA { get; set; }
        public int ES { get; set; }
    }
}
