//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDicountCoupen
    {
        public int ID { get; set; }
        public Nullable<int> BDID { get; set; }
        public string CoupenCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ValidityDays { get; set; }
        public Nullable<decimal> Day1Dis { get; set; }
        public Nullable<decimal> Day2Dis { get; set; }
        public Nullable<decimal> Day3Dis { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string UsedBy { get; set; }
        public Nullable<System.DateTime> FirstUsedDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
