//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeeDetail
    {
        public int Id { get; set; }
        public int FeeAmount { get; set; }
        public int Priority { get; set; }
        public int PaymentMode { get; set; }
        public int ACID { get; set; }
        public int SyllabusID { get; set; }
        public int GradeId { get; set; }
        public int StreamID { get; set; }
        public int CourseID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string Description { get; set; }
    }
}
