//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGroup
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int AcademicYearID { get; set; }
        public int SyllabusID { get; set; }
        public int ClassID { get; set; }
        public int StreamID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int DeletedBy { get; set; }
        public System.DateTime DeletedDateTime { get; set; }
        public int IsDeleted { get; set; }
    }
}
