//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGroup
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> AcademicYearID { get; set; }
        public Nullable<int> SyllabusID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
