//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Fee
    {
        public int ID { get; set; }
        public string RegID { get; set; }
        public string FeePayTerm { get; set; }
        public string DiscountPer { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<int> InstallmentMode { get; set; }
        public Nullable<System.DateTime> PaymentDt { get; set; }
        public Nullable<System.DateTime> PaymentDueDt { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
