//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Fee_receipt
    {
        public int Id { get; set; }
        public string FeeID { get; set; }
        public Nullable<int> StudentFeeID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TransactionNo { get; set; }
        public Nullable<System.DateTime> PaymentDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
