//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Payment_History
    {
        public int ID { get; set; }
        public string RegID { get; set; }
        public string paymentMode { get; set; }
        public string paymentType { get; set; }
        public string OrderID { get; set; }
        public string PaymentID { get; set; }
        public string Signature { get; set; }
        public string Amount { get; set; }
        public string DiscountUsed { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> FeeID { get; set; }
    }
}
