//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Mark_Scored
    {
        public int ID { get; set; }
        public string RegID { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> MarkObtained { get; set; }
        public Nullable<decimal> MaxMark { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
    }
}
