//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Parent_Basic
    {
        public int Id { get; set; }
        public string ParentName { get; set; }
        public string RelationShip { get; set; }
        public string MobileNumber { get; set; }
        public string WhatsAppNumber { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public string Emirates { get; set; }
        public string Occupation { get; set; }
        public string CompanyName { get; set; }
        public string HouseName { get; set; }
        public string State { get; set; }
        public string Dstrict { get; set; }
        public string Place { get; set; }
        public string PO { get; set; }
        public string PIN { get; set; }
        public string RegId { get; set; }
        public byte[] FatherSignature { get; set; }
        public byte[] StudentSignature { get; set; }
    }
}
