//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Fee_Payment_Details
    {
        public int Id { get; set; }
        public string FeeID { get; set; }
        public Nullable<int> ACID { get; set; }
        public Nullable<int> SyllabusID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> TempStudId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TransactionNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
