//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent_Payment_Terms
    {
        public int ID { get; set; }
        public string ReferenceCode { get; set; }
        public string RegID { get; set; }
        public string CourseSelected { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string PaymentType { get; set; }
        public string TransactionID { get; set; }
        public byte[] UploadSlip { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> DeletedDt { get; set; }
    }
}
