//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfocusLearningApp.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTeachers_Registration
    {
        public int Id { get; set; }
        public string TeachRegId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string WhatsApp { get; set; }
        public string PrimarySubject { get; set; }
        public string SecondarySubject { get; set; }
        public string Location { get; set; }
        public string Street { get; set; }
        public string Address { get; set; }
        public string PO { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public string MiddleName { get; set; }
        public string StudentGrade { get; set; }
        public string Weekdays { get; set; }
        public string Weekends { get; set; }
        public string Time { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string MobileNumber { get; set; }
    }
}
